export enum ValidateProfileError {
    INCORRECT_NAME_DATA = 'INCORRECT_NAME_DATA',
    INCORRECT_FULL_NAME_DATA = 'INCORRECT_FULL_NAME_DATA',
    INCORRECT_AGE_DATA = 'INCORRECT_AGE_DATA',
    INCORRECT_SECOND_NAME_DATA = 'INCORRECT_SECOND_NAME_DATA',
    INCORRECT_COUNTRY_DATA = 'INCORRECT_COUNTRY_DATA',
    SERVER_ERROR = 'SERVER_ERROR',
    NO_DATA = 'NO_DATA',
}
